ingress:
  enabled: true
  hosts: [awx.k8s.touist.eu]
  annotations:
    kubernetes.io/ingress.class: traefik
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts: [awx.k8s.touist.eu]
      secretName: awx-example-tls
