server:
  ingress:
    enabled: true
    hosts: [prometheus.kube.maelvls.dev]
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      - hosts: [prometheus.kube.maelvls.dev]
        secretName: prometheus-example-tls
