image:
  tag: latest
ingress:
  enabled: true
  hosts: [quote.kube.maelvls.dev]
  annotations:
    kubernetes.io/ingress.class: traefik
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts: [quote.kube.maelvls.dev]
      secretName: quote-example-tls
