service:
  type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/protocol: http
  hosts: [vault.kube.maelvls.dev]
  tls:
    - hosts: [vault.kube.maelvls.dev]
      secretName: vault-example-tls
vault:
  # A YAML representation of a final vault config.json file.
  # See https://www.vaultproject.io/docs/configuration/ for more
  # information.
  config:
    dev: "true"
    storage:
      gcs:
        bucket: vault-storage
        credentials_file: /vault/vault-storage-cred-file/credentials.json
    listener:
      tcp:
        tls_disable: "true"
        tls_cert_file: /vault/tls/tls.crt
        tls_key_file: /vault/tls/tls.key

  logLevel: "debug"
  extraVolumes:
    - name: vault-tls
      secret:
        secretName: vault-example-tls
    - name: vault-storage
      secret:
        secretName: vault-storage-cred-file
  extraVolumeMounts:
    - name: vault-tls
      mountPath: /vault/tls
      readOnly: true
    - name: vault-storage
      mountPath: /vault/vault-storage-cred-file
      readOnly: true
